import { AppLayout } from "@/components/layout/app-layout";
import { notoSans } from "@/config";
import type { Metadata } from "next";
import AppProvider from "./app-provider";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: {
    template: "%s | Hacker News",
    default: "Hacker News",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSans.className} antialiased`}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
        <AppProvider>
          <AppLayout>{children}</AppLayout>
        </AppProvider>
        <div id="portal-root" />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
